export const MOCK_SPEAKERS = [
  {
    id: "maria-garcia",
    name: "Maria Garcia",
    bio: "Senior Frontend Engineer con 8 anos de experiencia",
    photo_url: "",
    company: "Google",
    role: "Staff Engineer",
    topics: ["Web", "Angular", "TypeScript"],
    social_links: { linkedin: "https://linkedin.com/in/example" },
    talk_ids: [],
  },
  {
    id: "carlos-lopez",
    name: "Carlos Lopez",
    bio: "Cloud Architect y GDE en Google Cloud",
    photo_url: "",
    company: "AWS",
    role: "Solutions Architect",
    topics: ["Cloud", "Kubernetes", "DevOps"],
    social_links: {},
    talk_ids: [],
  },
  {
    id: "ana-torres",
    name: "Ana Torres",
    bio: "ML Engineer especializada en NLP",
    photo_url: "",
    company: "Meta",
    role: "ML Engineer",
    topics: ["AI", "Machine Learning", "Python"],
    social_links: { github: "https://github.com/example" },
    talk_ids: [],
  },
];

export const MOCK_EVENTS = [
  {
    id: "devfest-preview",
    title: "DevFest Preview 2026",
    description: "Evento de preview para desarrollo",
    date: "2026-06-15T09:00:00",
    end_time: "05:00 PM",
    venue: "Universidad Nacional",
    venue_address: "Av Principal 123",
    venue_map_url: "",
    image_url: "",
    topics: ["AI", "Cloud", "Web"],
    speaker_ids: ["maria-garcia"],
    registration_url: "",
    materials: {},
    agenda: [],
  },
];

export const MOCK_TEAM = [
  {
    id: "dev-user-1",
    name: "Juan Preview",
    role: "Leadership",
    photo_url: "",
    bio: "Organizador de ejemplo",
    social_links: { linkedin: "https://linkedin.com" },
    type: "organizer" as const,
    tags: ["Cloud", "Python"],
  },
  {
    id: "dev-user-2",
    name: "Laura Preview",
    role: "Technology",
    photo_url: "",
    bio: "Miembro de ejemplo",
    social_links: {},
    type: "member" as const,
    tags: ["React", "TypeScript"],
  },
];

export const MOCK_SPONSORS = [
  {
    name: "Google",
    logo_url: "",
    url: "https://google.com",
    sector: "Tecnologia",
    description: "Sponsor principal de ejemplo",
    featured: true,
  },
  {
    name: "GitHub",
    logo_url: "",
    url: "https://github.com",
    sector: "Software",
    description: "Sponsor de ejemplo",
    featured: false,
  },
];

export const MOCK_STATS = {
  total_members: 1000,
  total_events: 50,
  total_talks: 32,
  total_speakers: 25,
  years_active: 10,
  total_organizers: 7,
  developers_mentored: 200,
  total_sponsors: 15,
  annual_support: "$50k",
  sponsored_events: 100,
  developers_reached: 5000,
  active_volunteers: 50,
  volunteer_hours: 1500,
  events_supported: 100,
  volunteer_areas: 9,
  updated_at: new Date().toISOString(),
};

export const MOCK_USERS = [
  {
    uid: "dev-admin",
    email: "admin@preview.dev",
    displayName: "Admin Preview",
    photoURL: "",
    role: "admin",
    lastLoginAt: { _seconds: Math.floor(Date.now() / 1000) },
  },
];

export const MOCK_FORMS = [
  {
    id: "preview-form",
    name: "Formulario de Preview",
    spreadsheet_id: "mock",
    sheet_name: "Sheet1",
    is_public: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_FORM_RESPONSES = {
  headers: [
    "Marca temporal",
    "Nombre completo",
    "Correo electronico",
    "Empresa / Organizacion",
    "Cargo actual",
    "Telefono",
    "Ciudad",
    "Titulo de la charla o taller",
    "Descripcion de la propuesta",
    "Nivel de la charla",
    "Foto del speaker",
    "LinkedIn",
    "Titulo de la charla o taller propuesto para el evento",
    "¿Cuantos participantes para el evento de una charla o taller?",
    "¿Nivel de la charla o taller que propones para este evento?",
    "¿Tienes experiencia previa dando charlas o talleres en eventos de tecnologia?",
    "¿Cual es tu principal motivacion para participar como speaker en este evento?",
  ],
  rows: [
    [
      "4/3/2026 15:32:04",
      "Maria Garcia Fernandez",
      "maria.garcia@google.com",
      "Google",
      "Staff Frontend Engineer",
      "+51 987654321",
      "Lima, Peru",
      "Arquitectura de micro-frontends con Angular y Module Federation",
      "En esta charla exploraremos como implementar micro-frontends en aplicaciones empresariales usando Angular y Webpack Module Federation.",
      "Intermedio",
      "https://drive.google.com/file/d/1abc123/view",
      "https://linkedin.com/in/mariagarcia",
      "Micro-frontends con Angular",
      "Charla (50 minutos)",
      "Intermedio",
      "Si, 5 eventos internacionales incluyendo NgConf y Google I/O Extended",
      "Compartir mi experiencia con la comunidad de Ica",
    ],
    [
      "4/5/2026 09:15:22",
      "Carlos Alberto Lopez Ruiz",
      "carlos.lopez@aws.com",
      "Amazon Web Services",
      "Principal Solutions Architect",
      "+51 912345678",
      "Ica, Peru",
      "Construyendo arquitecturas serverless con AWS Lambda y Google Cloud Functions",
      "Comparativa practica entre AWS Lambda y Google Cloud Functions con caso real de migracion.",
      "Avanzado",
      "https://drive.google.com/file/d/2def456/view",
      "https://linkedin.com/in/carloslopez",
      "Serverless en la practica: AWS vs GCP",
      "Charla (50 minutos)",
      "Avanzado",
      "Si, speaker frecuente en AWS Summits y GDG events en Latinoamerica",
      "Quiero mostrar que serverless es accesible para equipos pequenos",
    ],
    [
      "4/5/2026 11:45:33",
      "Ana Maria Torres Vega",
      "ana.torres@meta.com",
      "Meta",
      "Senior ML Engineer",
      "+51 976543210",
      "Arequipa, Peru",
      "Introduccion a LLMs: desde la teoria hasta tu primera aplicacion con Gemini",
      "Taller practico donde los asistentes construiran una aplicacion de chat usando la API de Gemini.",
      "Basico",
      "https://drive.google.com/file/d/3ghi789/view",
      "https://linkedin.com/in/anatorres",
      "Workshop: Tu primera app con Gemini API",
      "Taller (2 horas)",
      "Basico",
      "Si, he dado talleres en Meta Developer Circles y GDG Cloud Lima",
      "La IA generativa esta cambiando todo y quiero ayudar a mas personas a empezar",
    ],
    [
      "4/6/2026 08:20:11",
      "Roberto Sanchez Diaz",
      "roberto.sanchez@startupxyz.com",
      "StartupXYZ",
      "CTO & Co-founder",
      "+51 965432109",
      "Cusco, Peru",
      "De 0 a produccion: como lanzamos nuestra startup usando solo herramientas de Google",
      "Historia real de como construimos y escalamos nuestra startup usando Firebase, Cloud Run, Flutter y BigQuery.",
      "Basico",
      "",
      "https://linkedin.com/in/robertosanchez",
      "De cero a produccion con Google Cloud",
      "Charla (30 minutos)",
      "Basico",
      "No, seria mi primera vez como speaker",
      "Quiero compartir nuestra historia para inspirar a emprendedores en Ica",
    ],
    [
      "4/7/2026 14:55:48",
      "Lucia Mendoza Paredes",
      "lucia.mendoza@university.edu.pe",
      "Universidad Nacional San Luis Gonzaga",
      "Docente investigadora",
      "+51 954321098",
      "Ica, Peru",
      "IA aplicada a la agricultura: caso de estudio en el valle de Ica",
      "Resultados de investigacion usando vision por computadora para detectar plagas en cultivos de uva.",
      "Intermedio",
      "https://drive.google.com/file/d/5mno234/view",
      "",
      "Computer Vision para agricultura en Ica",
      "Charla (50 minutos)",
      "Intermedio",
      "Si, ponencias en congresos academicos nacionales e internacionales",
      "Mostrar como la tecnologia puede resolver problemas reales de nuestra region",
    ],
    [
      "4/8/2026 10:30:00",
      "Diego Fernando Quispe Mamani",
      "diego.quispe@consultant.pe",
      "Independiente",
      "Cloud Consultant & GDE",
      "+51 943210987",
      "Lima, Peru",
      "Kubernetes en la practica: patrones de deployment para equipos pequenos",
      "Patrones simplificados de deployment usando GKE Autopilot, Helm charts y GitOps con ArgoCD.",
      "Avanzado",
      "https://drive.google.com/file/d/6pqr567/view",
      "https://linkedin.com/in/diegoquispe",
      "Kubernetes simplificado para equipos pequenos",
      "Charla (50 minutos)",
      "Avanzado",
      "Si, GDE en Cloud y speaker en KubeCon, DevFest y Cloud Next",
      "Desmitificar Kubernetes y mostrar que no es solo para empresas grandes",
    ],
    [
      "4/8/2026 16:12:37",
      "Valentina Rojas Castro",
      "valentina.rojas@designstudio.com",
      "Design Studio Peru",
      "Lead UX Designer",
      "+51 932109876",
      "Ica, Peru",
      "Diseno inclusivo: como crear interfaces accesibles que todos puedan usar",
      "Taller sobre interfaces web accesibles siguiendo WCAG 2.2 con herramientas de testing.",
      "Basico",
      "",
      "https://linkedin.com/in/valentinarojas",
      "Taller de accesibilidad web con herramientas reales",
      "Taller (2 horas)",
      "Basico",
      "Si, facilitadora en workshops de UX en Peru y Chile",
      "La accesibilidad es un derecho, no un feature opcional",
    ],
    [
      "4/9/2026 09:05:19",
      "Andres Felipe Morales",
      "andres.morales@fintech.co",
      "FinTech Colombia",
      "Backend Lead",
      "+57 3001234567",
      "Bogota, Colombia",
      "Event-driven architecture con Cloud Pub/Sub y Eventarc",
      "Arquitectura basada en eventos para procesar 10M de transacciones diarias.",
      "Avanzado",
      "https://drive.google.com/file/d/8vwx012/view",
      "https://linkedin.com/in/andresmorales",
      "Event-driven architecture a escala",
      "Charla (50 minutos)",
      "Avanzado",
      "Si, conferencias en Colombia, Mexico y Argentina",
      "Compartir patrones que realmente funcionan en produccion con trafico real",
    ],
    [
      "4/10/2026 13:40:55",
      "Camila Herrera Soto",
      "camila.herrera@edutech.pe",
      "EduTech Peru",
      "Product Manager",
      "+51 921098765",
      "Lima, Peru",
      "Como la IA esta transformando la educacion en Latinoamerica",
      "Panel sobre el impacto de IA generativa en la educacion con demos de tutores virtuales.",
      "Basico",
      "https://drive.google.com/file/d/9yz345/view",
      "https://linkedin.com/in/camilaherrera",
      "IA en educacion: demos y casos reales",
      "Charla (30 minutos)",
      "Basico",
      "No, pero tengo experiencia presentando en conferencias de educacion",
      "La IA puede democratizar el acceso a educacion de calidad en Latam",
    ],
    [
      "4/10/2026 17:22:08",
      "Miguel Angel Vargas",
      "miguel.vargas@devops.io",
      "DevOps Solutions",
      "SRE Engineer",
      "+51 910987654",
      "Ica, Peru",
      "Observabilidad 360: logs, metricas y traces con Google Cloud Operations",
      "Taller hands-on configurando Cloud Logging, Cloud Monitoring y Cloud Trace.",
      "Intermedio",
      "https://drive.google.com/file/d/0abc678/view",
      "https://linkedin.com/in/miguelvargas",
      "Observabilidad completa con Google Cloud Operations",
      "Taller (2 horas)",
      "Intermedio",
      "Si, instructor certificado en Google Cloud y speaker en DevFest Ica 2025",
      "Quiero que los developers de Ica aprendan a monitorear sus apps profesionalmente",
    ],
    [
      "4/11/2026 08:15:30",
      "Isabella Martinez Luna",
      "isabella.martinez@agency.pe",
      "Digital Agency Peru",
      "Marketing Director",
      "+51 909876543",
      "Ica, Peru",
      "Growth hacking con Google Analytics 4 y BigQuery",
      "Como usamos GA4 + BigQuery para triplicar la conversion de nuestros clientes.",
      "Intermedio",
      "",
      "https://linkedin.com/in/isabellamartinez",
      "Growth hacking con datos: GA4 + BigQuery",
      "Charla (30 minutos)",
      "Intermedio",
      "Si, ponencias en eventos de marketing digital en Peru",
      "Los datos son el nuevo petroleo y quiero enseniar a usarlos correctamente",
    ],
  ],
};
